# Generated by Django 5.1.3 on 2024-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horoscope_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_sign', models.CharField(max_length=30)),
                ('star', models.CharField(max_length=30)),
                ('gotra', models.CharField(max_length=30)),
                ('manglik', models.CharField(max_length=30)),
                ('shani', models.CharField(max_length=30)),
                ('horoscope_match', models.CharField(max_length=30)),
                ('place_of_birth', models.CharField(max_length=30)),
                ('place_of_country', models.CharField(max_length=30)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('am_pm', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
